#include "ui/components/theme.h"
#include <math.h>

const Color ColorPaper  = {0xE0, 0xE0, 0xDA, 0xFF};
const Color ColorShadow = {0xA0, 0xA0, 0x90, 0xFF};
const Color ColorDGreen = {0x00, 0xCC, 0x00, 0xFF};
const Color ColorDark1  = {0x33, 0x33, 0x33, 0xFF};
const Color ColorDark2  = {0x1A, 0x1A, 0x1A, 0xFF};
const Color ColorDark3  = {0x0D, 0x0D, 0x0D, 0xFF};
const Color ColorBGUtil = {0x22, 0x22, 0x22, 0xFF};
const Color ColorBlack  = {0x00, 0x00, 0x00, 0xFF};
const Color ColorWhite  = {0xFF, 0xFF, 0xFF, 0xFF};
const Color ColorRed    = {0xFF, 0x00, 0x00, 0xFF};
const Color ColorOrange = {0xFF, 0x80, 0x00, 0xFF};
const Color ColorBlue   = {0x00, 0x78, 0xFF, 0xFF};
const Color ColorCue    = {255, 165, 0, 255};
const Color ColorGray   = {0x55, 0x55, 0x55, 0xFF};
const Color ColorGreen  = {0x00, 0xFF, 0x00, 0xFF};
const Color ColorYellow = {0xFF, 0xFF, 0x00, 0xFF};
const Color ColorPink   = {0xFF, 0x00, 0xFF, 0xFF};


float UI_CurrScale = 1.0f;
float UI_OffsetX = 0.0f;
float UI_OffsetY = 0.0f;
bool UI_BoldEnabled = true;

void UI_UpdateScale(void) {
    // Primary scaling anchor is height to maintain consistent vertical layout density.
    // Horizontal layout becomes responsive (waveforms stretch/contract).
    UI_CurrScale = (float)GetScreenHeight() / REF_HEIGHT;
    
    // In responsive mode, we occupy the full window native area.
    UI_OffsetX = 0;
    UI_OffsetY = 0;
}

Vector2 UIGetMousePosition(void) {
    Vector2 m = GetMousePosition();
    return (Vector2){ m.x - UI_OffsetX, m.y - UI_OffsetY };
}

static Vector2 g_touchStartPos = { -1.0f, -1.0f };
static float g_touchDragDistance = 0.0f;

#if defined(PLATFORM_DRM) || (defined(__linux__) && !defined(__ANDROID__))
extern bool Evdev_IsTouchDown(void);
extern bool Evdev_IsTouchPressed(void);
extern bool Evdev_IsTouchReleased(void);
#endif

static double g_lastMousePressTime = -1.0;
static double g_lastMouseReleaseTime = -1.0;
static bool g_mouseWasDown = false;

#define MOUSE_RELEASE_DEBOUNCE_SEC 0.15

bool UI_IsPressed(void) {
    double now = GetTime();
    bool mousePressed = IsMouseButtonPressed(MOUSE_LEFT_BUTTON);
    bool mouseReleased = IsMouseButtonReleased(MOUSE_LEFT_BUTTON);

    if (mousePressed) {
        g_lastMousePressTime = now;
        g_mouseWasDown = true;
    }
    if (mouseReleased) {
        g_lastMouseReleaseTime = now;
        g_mouseWasDown = false;
    }

    bool pressed = false;

    // 1. Mouse Click Support with Release Debounce
    if (mousePressed) {
        if (g_lastMouseReleaseTime < 0.0 || (now - g_lastMouseReleaseTime) >= MOUSE_RELEASE_DEBOUNCE_SEC) {
            pressed = true;
        }
    }

    // 2. Touch Tap Support (Ignore GESTURE_TAP generated by mouse release)
    if (!pressed && IsGestureDetected(GESTURE_TAP)) {
        bool isFromMouseRelease = g_mouseWasDown ||
                                  (g_lastMousePressTime >= 0.0 && (now - g_lastMousePressTime) < 0.25) ||
                                  (g_lastMouseReleaseTime >= 0.0 && (now - g_lastMouseReleaseTime) < 0.25);
        if (!isFromMouseRelease) {
            pressed = true;
        }
    }

#if defined(PLATFORM_DRM) || (defined(__linux__) && !defined(__ANDROID__))
    if (Evdev_IsTouchPressed()) pressed = true;
#endif
    return pressed;
}

bool UI_IsDown(void) {
    bool down = IsMouseButtonDown(MOUSE_LEFT_BUTTON) || GetTouchPointCount() > 0;
#if defined(PLATFORM_DRM) || (defined(__linux__) && !defined(__ANDROID__))
    if (Evdev_IsTouchDown()) down = true;
#endif
    return down;
}

bool UI_IsReleased(void) {
    double now = GetTime();
    bool mouseReleased = IsMouseButtonReleased(MOUSE_LEFT_BUTTON);
    if (mouseReleased) {
        g_lastMouseReleaseTime = now;
        g_mouseWasDown = false;
    }

    bool released = mouseReleased;
    if (!released && IsGestureDetected(GESTURE_TAP)) {
        bool isFromMouse = g_mouseWasDown ||
                           (g_lastMousePressTime >= 0.0 && (now - g_lastMousePressTime) < 0.25) ||
                           (g_lastMouseReleaseTime >= 0.0 && (now - g_lastMouseReleaseTime) < 0.25);
        if (!isFromMouse) {
            released = true;
        }
    }

#if defined(PLATFORM_DRM) || (defined(__linux__) && !defined(__ANDROID__))
    if (Evdev_IsTouchReleased()) released = true;
#endif
    return released;
}

void UI_UpdateTouchState(void) {
    Vector2 m = UIGetMousePosition();
    if (UI_IsPressed()) {
        g_touchStartPos = m;
        g_touchDragDistance = 0.0f;
    } else if (UI_IsDown()) {
        float dx = m.x - g_touchStartPos.x;
        float dy = m.y - g_touchStartPos.y;
        float dist = (float)sqrt((double)(dx * dx + dy * dy));
        if (dist > g_touchDragDistance) {
            g_touchDragDistance = dist;
        }
    }
}

static double g_lastUIClickTime = -1.0;

bool UICheckClick(Rectangle rect) {
    double now = GetTime();
    if (!UI_IsReleased()) return false;
    if (g_lastUIClickTime > 0.0 && (now - g_lastUIClickTime) < 0.12) return false;
    if (g_touchDragDistance >= S(22.0f)) return false;
    if (!CheckCollisionPointRec(g_touchStartPos, rect) && !CheckCollisionPointRec(UIGetMousePosition(), rect)) return false;
    
    // Consume click so no subsequent check or frame re-fires
    g_touchDragDistance = 999.0f;
    g_lastUIClickTime = now;
    return true;
}

float UIGetTouchDragDistance(void) {
    return g_touchDragDistance;
}

Vector2 UIGetTouchStartPos(void) {
    return g_touchStartPos;
}

float S(float v) {
    return v * UI_CurrScale;
}

int Si(int v) {
    return (int)(v * UI_CurrScale);
}
