#ifndef DEFAULTS_H
#define DEFAULTS_H

static const char* DEFAULT_MIDI_LOOPMIDI = "<?xml version='1.0' encoding='utf-8'?>\n"
"<UNXMIDIPreset schemaVersion=\"1\">\n"
"    <info>\n"
"        <name>LoopMIDI Default</name>\n"
"        <author>UNX</author>\n"
"        <description>Default mapping template for LoopMIDI</description>\n"
"    </info>\n"
"    <controller id=\"LoopMIDI\">\n"
"        <controls>\n"
"            <control><group>[Channel1]</group><key>play</key><status>0x90</status><midino>0x0B</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel1]</group><key>cue_default</key><status>0x90</status><midino>0x0C</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel1]</group><key>pfl</key><status>0x90</status><midino>0x54</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel1]</group><key>volume</key><status>0xB0</status><midino>0x04</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel1]</group><key>fader</key><status>0xB0</status><midino>0x13</midino><options><Normal/></options></control>\n"
"            <control><group>[EqualizerRack1_[Channel1]_Effect1]</group><key>parameter3</key><status>0xB0</status><midino>0x07</midino><options><Normal/></options></control>\n"
"            <control><group>[EqualizerRack1_[Channel1]_Effect1]</group><key>parameter2</key><status>0xB0</status><midino>0x0B</midino><options><Normal/></options></control>\n"
"            <control><group>[EqualizerRack1_[Channel1]_Effect1]</group><key>parameter1</key><status>0xB0</status><midino>0x0F</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel1]</group><key>colorfx_value</key><status>0xB0</status><midino>0x15</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel1]</group><key>PioneerDDJ400.jogTurn</key><status>0xB0</status><midino>0x22</midino><options><Script-Binding/></options></control>\n"
"            <control><group>[Channel1]</group><key>PioneerDDJ400.shiftPressed</key><status>0x90</status><midino>0x3F</midino><options><Script-Binding/></options></control>\n"
"            <control><group>[Channel2]</group><key>play</key><status>0x91</status><midino>0x0B</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel2]</group><key>cue_default</key><status>0x91</status><midino>0x0C</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel2]</group><key>pfl</key><status>0x91</status><midino>0x54</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel2]</group><key>volume</key><status>0xB1</status><midino>0x04</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel2]</group><key>fader</key><status>0xB1</status><midino>0x13</midino><options><Normal/></options></control>\n"
"            <control><group>[EqualizerRack1_[Channel2]_Effect1]</group><key>parameter3</key><status>0xB1</status><midino>0x07</midino><options><Normal/></options></control>\n"
"            <control><group>[EqualizerRack1_[Channel2]_Effect1]</group><key>parameter2</key><status>0xB1</status><midino>0x0B</midino><options><Normal/></options></control>\n"
"            <control><group>[EqualizerRack1_[Channel2]_Effect1]</group><key>parameter1</key><status>0xB1</status><midino>0x0F</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel2]</group><key>colorfx_value</key><status>0xB1</status><midino>0x15</midino><options><Normal/></options></control>\n"
"            <control><group>[Master]</group><key>crossfader</key><status>0xB0</status><midino>0x1F</midino><options><Normal/></options></control>\n"
"            <control><group>[Master]</group><key>volume</key><status>0xB0</status><midino>0x14</midino><options><Normal/></options></control>\n"
"            <control><group>[Master]</group><key>beatfx_drywet</key><status>0xB0</status><midino>0x1B</midino><options><Normal/></options></control>\n"
"            <control><group>[Master]</group><key>beatfx_time</key><status>0xB0</status><midino>0x1C</midino><options><Normal/></options></control>\n"
"            <control><group>[Master]</group><key>beatfx_select</key><status>0xB0</status><midino>0x1E</midino><options><Normal/></options></control>\n"
"            <control><group>[Master]</group><key>beatfx_on</key><status>0x90</status><midino>0x47</midino><options><Normal/></options></control>\n"
"            <control><group>[Master]</group><key>beatfx_channel</key><status>0x90</status><midino>0x48</midino><options><Normal/></options></control>\n"
"            <control><group>[Library]</group><key>browse</key><status>0xB0</status><midino>0x3C</midino><options><SelectKnob/></options></control>\n"
"            <control><group>[Library]</group><key>enter</key><status>0x90</status><midino>0x3D</midino><options><Normal/></options></control>\n"
"            <control><group>[Library]</group><key>back</key><status>0x90</status><midino>0x3E</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel1]</group><key>loadA</key><status>0x90</status><midino>0x46</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel2]</group><key>loadB</key><status>0x91</status><midino>0x46</midino><options><Normal/></options></control>\n"
"        </controls>\n"
"    </controller>\n"
"</UNXMIDIPreset>";

static const char* DEFAULT_MIDI_TEMPLATE = "<?xml version='1.0' encoding='utf-8'?>\n"
"<UNXMIDIPreset schemaVersion=\"1\">\n"
"    <info>\n"
"        <name>Professional Template</name>\n"
"        <author>UNX</author>\n"
"        <description>Full mapping template based on Pioneer DDJ-SX/SB standards.</description>\n"
"    </info>\n"
"    <controller id=\"Template\">\n"
"        <controls>\n"
"            <control><group>[Channel1]</group><key>play</key><status>0x00</status><midino>0x00</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel1]</group><key>cue_default</key><status>0x00</status><midino>0x00</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel1]</group><key>volume</key><status>0x00</status><midino>0x00</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel2]</group><key>play</key><status>0x00</status><midino>0x00</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel2]</group><key>cue_default</key><status>0x00</status><midino>0x00</midino><options><Normal/></options></control>\n"
"            <control><group>[Channel2]</group><key>volume</key><status>0x00</status><midino>0x00</midino><options><Normal/></options></control>\n"
"            <!-- (Truncated for brevity in defaults.h, full template in repo) -->\n"
"        </controls>\n"
"    </controller>\n"
"</UNXMIDIPreset>";

#endif
